name: qa

on:
  push:
    branches:
      - qa

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Run secrets.py
        run: python3 .github/workflows/secrets.py nancy morado