name: qa

on:
  push:
    branches:
      - qa

jobs:
  qa:
    runs-on: ubuntu-latest
    environment:
      name: qa
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Run secrets.py
        run: |
         python3 secrets.py ${{ secrets.USUARIO }} ${{ secrets.PASS }}
         echo "Mi usuario es: ${{ secrets.USUARIO }}"
         echo "Mi pass es: ${{ secrets.PASS }}"

  mensaje:
    runs-on: ubuntu-latest
    steps:
      - name: Mensaje
        run: echo "Mensaje prueba"