name: main

on:
  pull_request:
    branches:
      - main

jobs:
  test_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Mensaje PR
        run: echo "Este es el mensaje del PR para job2"


